### ISSUE TITLE
Making-Things-Hard-on-Yourself. 翻译

### ISSUE THREAD

**Issue by 18628341919** [18628341919/Gladys#2]
原文地址：[Elizabeth L. Bjork and Robert Bjork](https://bjorklab.psych.ucla.edu/wp-content/uploads/sites/13/2016/04/EBjork_RBjork_2011.pdf)

**Comment by Lauren83** [comment]
青豆翻译任务part1初稿，请大家指正！
[https://github.com/Lauren83/Cards/blob/master/Part%201.md](https://github.com/Lauren83/Cards/blob/master/Part%201.md)

**Comment by gabriel-guobin** [comment]
郭斌翻译 Part2 初稿，大家多指正
地址：https://github.com/gabriel-guobin/Card/blob/master/Part2.md

为便于协作，对翻译的内容有哪些问题，可以通过下面的页面，逐句添加评论。

https://github.com/gabriel-guobin/Card/commit/0dcb013616729ca595d7eb50a97881778a299819?diff=unified

也可以通过 pull request 直接修改

**Comment by Yulianxia** [comment]
https://github.com/Yulianxia/lernen-Rekord/issues/16
@18628341919 comment里面是总结的要点，有几段合并了。但郭斌总结的前面部分我没找到

**Comment by gabriel-guobin** [comment]
@18628341919  关于Part1和Part2的修改建议，之前已经在原文提交了 [Pull Requests · 18628341919/Gladys](https://github.com/18628341919/Gladys/pulls)，当时为了便于修改，分成多个命令提交，可能有些过于繁琐，需要一一合并到原文中。我把之前提交的所有内容重新在fork的仓库中提交了修改，可能核对起来更方便些。

- 合并Part1和Part2后的文档：
  * [Gladys/Making Things Hard on Yourself.md at master · gabriel-guobin/Gladys](https://github.com/gabriel-guobin/Gladys/blob/master/Making%20Things%20Hard%20on%20Yourself.md)

- 提交修改的对比：
  * [修改了part1和part2的翻译（line1~111),逐条修改建议提交到pull request · gabriel-guobin/Gladys@42ae62e](https://github.com/gabriel-guobin/Gladys/commit/42ae62ef316ba2872c5c6720da284fc44cad299e)

@Yulianxia 关于Part1和Part2的要点总结。我之前没有get到还有这个任务，我尽快把Part1和 part2部分的要点总结一下。争取明天中午完成。


### 剩余任务:

- [ ] part1 & part2 的的要点总结。 @gabriel-guobin
- [ ] part3部分 @Yulianxia 的版本和 @18628341919 的版本差异较大，可能还需要沟通一下。
- [ ] part4部分的要点总结
- [ ] 截止日期，本周五怎样？

@18628341919 @Lauren83 @Yulianxia
